{
  "uid" : "14b1ea6b4e980ef2",
  "name" : "test__login",
  "fullName" : "test.conduit_panniangyan_test.TestConduit#test__login",
  "historyId" : "51625365f8691b6a7c0681b76565d3b2",
  "time" : {
    "start" : 1627899646619,
    "stop" : 1627899646619,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: setup() takes 0 positional arguments but 1 was given",
  "statusTrace" : "cls = <class '_pytest.runner.CallInfo'>\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7f09d2eb4af0>\nwhen = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:311: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:13: in pytest_runtest_setup\n    call_optional(item.parent.obj, \"setup\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nobj = <conduit_panniangyan_test.TestConduit object at 0x7f09d2e4db80>\nname = 'setup'\n\n    def call_optional(obj, name):\n        method = getattr(obj, name, None)\n        isfixture = hasattr(method, \"_pytestfixturefunction\")\n        if method is not None and not isfixture and callable(method):\n            # If there's any problems allow the exception to raise rather than\n            # silently ignoring them.\n>           method()\nE           TypeError: setup() takes 0 positional arguments but 1 was given\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:38: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "conduit_panniangyan_test"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az39-326"
  }, {
    "name" : "thread",
    "value" : "3652-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.conduit_panniangyan_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 17,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 17
      },
      "items" : [ {
        "uid" : "958382cf3a69dc38",
        "reportUrl" : "https://panniangyan.github.io/conduit/19//#testresult/958382cf3a69dc38",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627899220750,
          "stop" : 1627899220750,
          "duration" : 0
        }
      }, {
        "uid" : "48a7c7df1d1259cc",
        "reportUrl" : "https://panniangyan.github.io/conduit/18//#testresult/48a7c7df1d1259cc",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627898435342,
          "stop" : 1627898435342,
          "duration" : 0
        }
      }, {
        "uid" : "5f59a829d8b89e8a",
        "reportUrl" : "https://panniangyan.github.io/conduit/17//#testresult/5f59a829d8b89e8a",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52653): Max retries exceeded with url: /session/f04a3cdd168c74da301d0c38b9cb3db9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca1bfd7a60>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627896378762,
          "stop" : 1627896378762,
          "duration" : 0
        }
      }, {
        "uid" : "931722a827aa187f",
        "reportUrl" : "https://panniangyan.github.io/conduit/16//#testresult/931722a827aa187f",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60017): Max retries exceeded with url: /session/b1a5c94c7bc7022ef76dd2ebb8ba0f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a75135910>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627895212335,
          "stop" : 1627895212335,
          "duration" : 0
        }
      }, {
        "uid" : "3b7e26627e5bd366",
        "reportUrl" : "https://panniangyan.github.io/conduit/15//#testresult/3b7e26627e5bd366",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=43719): Max retries exceeded with url: /session/91742e4ead70df7aa6cbcad06f4f1bd2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe18d187070>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627892995899,
          "stop" : 1627892995899,
          "duration" : 0
        }
      }, {
        "uid" : "a9212700a9e2814d",
        "reportUrl" : "https://panniangyan.github.io/conduit/14//#testresult/a9212700a9e2814d",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'WebDriver' object has no attribute 'webdriver'",
        "time" : {
          "start" : 1627892617361,
          "stop" : 1627892617361,
          "duration" : 0
        }
      }, {
        "uid" : "2ec642fda151103",
        "reportUrl" : "https://panniangyan.github.io/conduit/12//#testresult/2ec642fda151103",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627888455626,
          "stop" : 1627888455626,
          "duration" : 0
        }
      }, {
        "uid" : "ef98815e0b6f4b1f",
        "reportUrl" : "https://panniangyan.github.io/conduit/11//#testresult/ef98815e0b6f4b1f",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829932554,
          "stop" : 1627829932554,
          "duration" : 0
        }
      }, {
        "uid" : "ae75b4a9865f788b",
        "reportUrl" : "https://panniangyan.github.io/conduit/10//#testresult/ae75b4a9865f788b",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829830033,
          "stop" : 1627829830033,
          "duration" : 0
        }
      }, {
        "uid" : "ee974a8c5e4853fc",
        "reportUrl" : "https://panniangyan.github.io/conduit/9//#testresult/ee974a8c5e4853fc",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829049979,
          "stop" : 1627829049979,
          "duration" : 0
        }
      }, {
        "uid" : "44c9c5f285bff926",
        "reportUrl" : "https://panniangyan.github.io/conduit/8//#testresult/44c9c5f285bff926",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627828717725,
          "stop" : 1627828717725,
          "duration" : 0
        }
      }, {
        "uid" : "a77d331c9548b4be",
        "reportUrl" : "https://panniangyan.github.io/conduit/7//#testresult/a77d331c9548b4be",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627828253686,
          "stop" : 1627828253686,
          "duration" : 0
        }
      }, {
        "uid" : "1131cb47a9095d9e",
        "reportUrl" : "https://panniangyan.github.io/conduit/6//#testresult/1131cb47a9095d9e",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627827066930,
          "stop" : 1627827066930,
          "duration" : 0
        }
      }, {
        "uid" : "15c8b1b29b083c57",
        "reportUrl" : "https://panniangyan.github.io/conduit/5//#testresult/15c8b1b29b083c57",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627819953893,
          "stop" : 1627819953893,
          "duration" : 0
        }
      }, {
        "uid" : "1ed5c683bc1d6430",
        "reportUrl" : "https://panniangyan.github.io/conduit/4//#testresult/1ed5c683bc1d6430",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818409150,
          "stop" : 1627818409150,
          "duration" : 0
        }
      }, {
        "uid" : "228f019dc4d103c",
        "reportUrl" : "https://panniangyan.github.io/conduit/3//#testresult/228f019dc4d103c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818158841,
          "stop" : 1627818158841,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "14b1ea6b4e980ef2.json",
  "parameterValues" : [ ]
}