{
  "uid" : "6765bd6067bab6a6",
  "name" : "test__add_new_article",
  "fullName" : "test.conduit_panniangyan_test.TestConduit#test__add_new_article",
  "historyId" : "16e1d08b48382b4f4da7f0942fe0871a",
  "time" : {
    "start" : 1627899646714,
    "stop" : 1627899646714,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: setup() takes 0 positional arguments but 1 was given",
  "statusTrace" : "cls = <class '_pytest.runner.CallInfo'>\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7f09d2eb4b80>\nwhen = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:311: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:13: in pytest_runtest_setup\n    call_optional(item.parent.obj, \"setup\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nobj = <conduit_panniangyan_test.TestConduit object at 0x7f09d3562ca0>\nname = 'setup'\n\n    def call_optional(obj, name):\n        method = getattr(obj, name, None)\n        isfixture = hasattr(method, \"_pytestfixturefunction\")\n        if method is not None and not isfixture and callable(method):\n            # If there's any problems allow the exception to raise rather than\n            # silently ignoring them.\n>           method()\nE           TypeError: setup() takes 0 positional arguments but 1 was given\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:38: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "conduit_panniangyan_test"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az39-326"
  }, {
    "name" : "thread",
    "value" : "3652-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.conduit_panniangyan_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 17,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 17
      },
      "items" : [ {
        "uid" : "f34caa9e0c3cbc4d",
        "reportUrl" : "https://panniangyan.github.io/conduit/19//#testresult/f34caa9e0c3cbc4d",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627899220854,
          "stop" : 1627899220854,
          "duration" : 0
        }
      }, {
        "uid" : "f43d032c0b80c3cc",
        "reportUrl" : "https://panniangyan.github.io/conduit/18//#testresult/f43d032c0b80c3cc",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627898435436,
          "stop" : 1627898435436,
          "duration" : 0
        }
      }, {
        "uid" : "ede45745d97d8805",
        "reportUrl" : "https://panniangyan.github.io/conduit/17//#testresult/ede45745d97d8805",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52653): Max retries exceeded with url: /session/f04a3cdd168c74da301d0c38b9cb3db9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca1beeb250>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627896379343,
          "stop" : 1627896379343,
          "duration" : 0
        }
      }, {
        "uid" : "78b0c0a6d5b27e30",
        "reportUrl" : "https://panniangyan.github.io/conduit/16//#testresult/78b0c0a6d5b27e30",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60017): Max retries exceeded with url: /session/b1a5c94c7bc7022ef76dd2ebb8ba0f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a74f25100>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627895212940,
          "stop" : 1627895212940,
          "duration" : 0
        }
      }, {
        "uid" : "2d247d09d26b70c8",
        "reportUrl" : "https://panniangyan.github.io/conduit/15//#testresult/2d247d09d26b70c8",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=43719): Max retries exceeded with url: /session/91742e4ead70df7aa6cbcad06f4f1bd2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe18d175220>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627892996448,
          "stop" : 1627892996448,
          "duration" : 0
        }
      }, {
        "uid" : "efc6fab8270d72c",
        "reportUrl" : "https://panniangyan.github.io/conduit/14//#testresult/efc6fab8270d72c",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'WebDriver' object has no attribute 'webdriver'",
        "time" : {
          "start" : 1627892617380,
          "stop" : 1627892617380,
          "duration" : 0
        }
      }, {
        "uid" : "215d162e779e5013",
        "reportUrl" : "https://panniangyan.github.io/conduit/12//#testresult/215d162e779e5013",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627888455647,
          "stop" : 1627888455647,
          "duration" : 0
        }
      }, {
        "uid" : "1bd94c2390382241",
        "reportUrl" : "https://panniangyan.github.io/conduit/11//#testresult/1bd94c2390382241",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829932576,
          "stop" : 1627829932576,
          "duration" : 0
        }
      }, {
        "uid" : "f0656d598ae7d0ad",
        "reportUrl" : "https://panniangyan.github.io/conduit/10//#testresult/f0656d598ae7d0ad",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829830060,
          "stop" : 1627829830060,
          "duration" : 0
        }
      }, {
        "uid" : "3715169e20d9585a",
        "reportUrl" : "https://panniangyan.github.io/conduit/9//#testresult/3715169e20d9585a",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829049999,
          "stop" : 1627829049999,
          "duration" : 0
        }
      }, {
        "uid" : "563f04df02071dea",
        "reportUrl" : "https://panniangyan.github.io/conduit/8//#testresult/563f04df02071dea",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627828717745,
          "stop" : 1627828717745,
          "duration" : 0
        }
      }, {
        "uid" : "d6ab8f81ec90e05a",
        "reportUrl" : "https://panniangyan.github.io/conduit/7//#testresult/d6ab8f81ec90e05a",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627828257188,
          "stop" : 1627828257188,
          "duration" : 0
        }
      }, {
        "uid" : "b8d72a427223736e",
        "reportUrl" : "https://panniangyan.github.io/conduit/6//#testresult/b8d72a427223736e",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627827070405,
          "stop" : 1627827070405,
          "duration" : 0
        }
      }, {
        "uid" : "1a5f0b159740170b",
        "reportUrl" : "https://panniangyan.github.io/conduit/5//#testresult/1a5f0b159740170b",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627819957405,
          "stop" : 1627819957405,
          "duration" : 0
        }
      }, {
        "uid" : "f933028cc164155c",
        "reportUrl" : "https://panniangyan.github.io/conduit/4//#testresult/f933028cc164155c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818412712,
          "stop" : 1627818412712,
          "duration" : 0
        }
      }, {
        "uid" : "32912c50c0d5e78d",
        "reportUrl" : "https://panniangyan.github.io/conduit/3//#testresult/32912c50c0d5e78d",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818162311,
          "stop" : 1627818162311,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "6765bd6067bab6a6.json",
  "parameterValues" : [ ]
}