{
  "uid" : "9da47073c87f7d27",
  "name" : "test__modify_article",
  "fullName" : "test.conduit_panniangyan_test.TestConduit#test__modify_article",
  "historyId" : "48424fbdb77766ff5c5c1958697f1417",
  "time" : {
    "start" : 1627899646780,
    "stop" : 1627899646780,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: setup() takes 0 positional arguments but 1 was given",
  "statusTrace" : "cls = <class '_pytest.runner.CallInfo'>\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7f09d2ec1b80>\nwhen = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:311: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:13: in pytest_runtest_setup\n    call_optional(item.parent.obj, \"setup\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nobj = <conduit_panniangyan_test.TestConduit object at 0x7f09d2e4daf0>\nname = 'setup'\n\n    def call_optional(obj, name):\n        method = getattr(obj, name, None)\n        isfixture = hasattr(method, \"_pytestfixturefunction\")\n        if method is not None and not isfixture and callable(method):\n            # If there's any problems allow the exception to raise rather than\n            # silently ignoring them.\n>           method()\nE           TypeError: setup() takes 0 positional arguments but 1 was given\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:38: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "conduit_panniangyan_test"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az39-326"
  }, {
    "name" : "thread",
    "value" : "3652-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.conduit_panniangyan_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 17,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 17
      },
      "items" : [ {
        "uid" : "e7cb1118f49c43b9",
        "reportUrl" : "https://panniangyan.github.io/conduit/19//#testresult/e7cb1118f49c43b9",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627899220923,
          "stop" : 1627899220923,
          "duration" : 0
        }
      }, {
        "uid" : "ecb4466fb9c4fe77",
        "reportUrl" : "https://panniangyan.github.io/conduit/18//#testresult/ecb4466fb9c4fe77",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627898435500,
          "stop" : 1627898435500,
          "duration" : 0
        }
      }, {
        "uid" : "eac944a9397d3da5",
        "reportUrl" : "https://panniangyan.github.io/conduit/17//#testresult/eac944a9397d3da5",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52653): Max retries exceeded with url: /session/f04a3cdd168c74da301d0c38b9cb3db9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca1c037220>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627896379716,
          "stop" : 1627896379716,
          "duration" : 0
        }
      }, {
        "uid" : "dbe5c35efd48043",
        "reportUrl" : "https://panniangyan.github.io/conduit/16//#testresult/dbe5c35efd48043",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60017): Max retries exceeded with url: /session/b1a5c94c7bc7022ef76dd2ebb8ba0f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a74f3d220>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627895213363,
          "stop" : 1627895213363,
          "duration" : 0
        }
      }, {
        "uid" : "dc6f9e84ad36f756",
        "reportUrl" : "https://panniangyan.github.io/conduit/15//#testresult/dc6f9e84ad36f756",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=43719): Max retries exceeded with url: /session/91742e4ead70df7aa6cbcad06f4f1bd2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe18d0fa2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627892996852,
          "stop" : 1627892996852,
          "duration" : 0
        }
      }, {
        "uid" : "34487d74e0e9b5c5",
        "reportUrl" : "https://panniangyan.github.io/conduit/14//#testresult/34487d74e0e9b5c5",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'WebDriver' object has no attribute 'webdriver'",
        "time" : {
          "start" : 1627892617393,
          "stop" : 1627892617393,
          "duration" : 0
        }
      }, {
        "uid" : "332fd55c71e41cad",
        "reportUrl" : "https://panniangyan.github.io/conduit/12//#testresult/332fd55c71e41cad",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627888455660,
          "stop" : 1627888455660,
          "duration" : 0
        }
      }, {
        "uid" : "9b569db877cfda8a",
        "reportUrl" : "https://panniangyan.github.io/conduit/11//#testresult/9b569db877cfda8a",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829932590,
          "stop" : 1627829932590,
          "duration" : 0
        }
      }, {
        "uid" : "8e6789af68828a69",
        "reportUrl" : "https://panniangyan.github.io/conduit/10//#testresult/8e6789af68828a69",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829830078,
          "stop" : 1627829830078,
          "duration" : 0
        }
      }, {
        "uid" : "e02ac8403810b394",
        "reportUrl" : "https://panniangyan.github.io/conduit/9//#testresult/e02ac8403810b394",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829050013,
          "stop" : 1627829050013,
          "duration" : 0
        }
      }, {
        "uid" : "56a6ded8a9567d3f",
        "reportUrl" : "https://panniangyan.github.io/conduit/8//#testresult/56a6ded8a9567d3f",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627828717758,
          "stop" : 1627828717758,
          "duration" : 0
        }
      }, {
        "uid" : "99c62a85d4246e91",
        "reportUrl" : "https://panniangyan.github.io/conduit/7//#testresult/99c62a85d4246e91",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627828259545,
          "stop" : 1627828259545,
          "duration" : 0
        }
      }, {
        "uid" : "4dd07acb3840782a",
        "reportUrl" : "https://panniangyan.github.io/conduit/6//#testresult/4dd07acb3840782a",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627827072744,
          "stop" : 1627827072744,
          "duration" : 0
        }
      }, {
        "uid" : "44598db23983878e",
        "reportUrl" : "https://panniangyan.github.io/conduit/5//#testresult/44598db23983878e",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627819959767,
          "stop" : 1627819959767,
          "duration" : 0
        }
      }, {
        "uid" : "420437d4482432d8",
        "reportUrl" : "https://panniangyan.github.io/conduit/4//#testresult/420437d4482432d8",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818415065,
          "stop" : 1627818415065,
          "duration" : 0
        }
      }, {
        "uid" : "36092c229d10065c",
        "reportUrl" : "https://panniangyan.github.io/conduit/3//#testresult/36092c229d10065c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818163713,
          "stop" : 1627818163713,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "9da47073c87f7d27.json",
  "parameterValues" : [ ]
}