{
  "uid" : "dd8f2bfc0c5d09b8",
  "name" : "test__import_data_from_file",
  "fullName" : "test.conduit_panniangyan_test.TestConduit#test__import_data_from_file",
  "historyId" : "514c1849c916d4c8c1b7f09004ee7cc9",
  "time" : {
    "start" : 1627899646745,
    "stop" : 1627899646745,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: setup() takes 0 positional arguments but 1 was given",
  "statusTrace" : "cls = <class '_pytest.runner.CallInfo'>\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7f09d2ec1430>\nwhen = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:311: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:13: in pytest_runtest_setup\n    call_optional(item.parent.obj, \"setup\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nobj = <conduit_panniangyan_test.TestConduit object at 0x7f09d2ed7af0>\nname = 'setup'\n\n    def call_optional(obj, name):\n        method = getattr(obj, name, None)\n        isfixture = hasattr(method, \"_pytestfixturefunction\")\n        if method is not None and not isfixture and callable(method):\n            # If there's any problems allow the exception to raise rather than\n            # silently ignoring them.\n>           method()\nE           TypeError: setup() takes 0 positional arguments but 1 was given\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:38: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "conduit_panniangyan_test"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az39-326"
  }, {
    "name" : "thread",
    "value" : "3652-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.conduit_panniangyan_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 17,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 17
      },
      "items" : [ {
        "uid" : "4e6be78e963b7de3",
        "reportUrl" : "https://panniangyan.github.io/conduit/19//#testresult/4e6be78e963b7de3",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627899220888,
          "stop" : 1627899220888,
          "duration" : 0
        }
      }, {
        "uid" : "c2febf7fc563b5c6",
        "reportUrl" : "https://panniangyan.github.io/conduit/18//#testresult/c2febf7fc563b5c6",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627898435468,
          "stop" : 1627898435468,
          "duration" : 0
        }
      }, {
        "uid" : "2ec58b8f32bdd2a3",
        "reportUrl" : "https://panniangyan.github.io/conduit/17//#testresult/2ec58b8f32bdd2a3",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52653): Max retries exceeded with url: /session/f04a3cdd168c74da301d0c38b9cb3db9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca1c05c0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627896379539,
          "stop" : 1627896379539,
          "duration" : 0
        }
      }, {
        "uid" : "79f64f676b841479",
        "reportUrl" : "https://panniangyan.github.io/conduit/16//#testresult/79f64f676b841479",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60017): Max retries exceeded with url: /session/b1a5c94c7bc7022ef76dd2ebb8ba0f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a74f11190>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627895213165,
          "stop" : 1627895213165,
          "duration" : 0
        }
      }, {
        "uid" : "2f17a8a9105caad7",
        "reportUrl" : "https://panniangyan.github.io/conduit/15//#testresult/2f17a8a9105caad7",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=43719): Max retries exceeded with url: /session/91742e4ead70df7aa6cbcad06f4f1bd2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe18d063be0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627892996667,
          "stop" : 1627892996667,
          "duration" : 0
        }
      }, {
        "uid" : "4bcc2915e8fa453a",
        "reportUrl" : "https://panniangyan.github.io/conduit/14//#testresult/4bcc2915e8fa453a",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'WebDriver' object has no attribute 'webdriver'",
        "time" : {
          "start" : 1627892617387,
          "stop" : 1627892617387,
          "duration" : 0
        }
      }, {
        "uid" : "fcb5182913d30349",
        "reportUrl" : "https://panniangyan.github.io/conduit/12//#testresult/fcb5182913d30349",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627888455653,
          "stop" : 1627888455653,
          "duration" : 0
        }
      }, {
        "uid" : "d83f0b11dfb1aa0f",
        "reportUrl" : "https://panniangyan.github.io/conduit/11//#testresult/d83f0b11dfb1aa0f",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829932583,
          "stop" : 1627829932583,
          "duration" : 0
        }
      }, {
        "uid" : "df83efd36471fa94",
        "reportUrl" : "https://panniangyan.github.io/conduit/10//#testresult/df83efd36471fa94",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829830070,
          "stop" : 1627829830070,
          "duration" : 0
        }
      }, {
        "uid" : "16c81366300bf03f",
        "reportUrl" : "https://panniangyan.github.io/conduit/9//#testresult/16c81366300bf03f",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829050006,
          "stop" : 1627829050006,
          "duration" : 0
        }
      }, {
        "uid" : "b493afe249b8d59d",
        "reportUrl" : "https://panniangyan.github.io/conduit/8//#testresult/b493afe249b8d59d",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627828717751,
          "stop" : 1627828717751,
          "duration" : 0
        }
      }, {
        "uid" : "bf325ae051530162",
        "reportUrl" : "https://panniangyan.github.io/conduit/7//#testresult/bf325ae051530162",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627828258355,
          "stop" : 1627828258355,
          "duration" : 0
        }
      }, {
        "uid" : "f82dcc0df2e3435b",
        "reportUrl" : "https://panniangyan.github.io/conduit/6//#testresult/f82dcc0df2e3435b",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627827071565,
          "stop" : 1627827071565,
          "duration" : 0
        }
      }, {
        "uid" : "d0ad10efd2db7f45",
        "reportUrl" : "https://panniangyan.github.io/conduit/5//#testresult/d0ad10efd2db7f45",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627819958574,
          "stop" : 1627819958574,
          "duration" : 0
        }
      }, {
        "uid" : "d769ea23dc7e4601",
        "reportUrl" : "https://panniangyan.github.io/conduit/4//#testresult/d769ea23dc7e4601",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818413877,
          "stop" : 1627818413877,
          "duration" : 0
        }
      }, {
        "uid" : "e3c28677a736ebfd",
        "reportUrl" : "https://panniangyan.github.io/conduit/3//#testresult/e3c28677a736ebfd",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818163526,
          "stop" : 1627818163526,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "dd8f2bfc0c5d09b8.json",
  "parameterValues" : [ ]
}