{
  "uid" : "2e6437c6b9464535",
  "name" : "test__pagination",
  "fullName" : "test.conduit_panniangyan_test.TestConduit#test__pagination",
  "historyId" : "e9939597f3edc0b6a86b00b225f9c777",
  "time" : {
    "start" : 1627899680263,
    "stop" : 1627899680263,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: setup() takes 0 positional arguments but 1 was given",
  "statusTrace" : "cls = <class '_pytest.runner.CallInfo'>\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7f6b1c65ce50>\nwhen = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:311: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:13: in pytest_runtest_setup\n    call_optional(item.parent.obj, \"setup\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nobj = <conduit_panniangyan_test.TestConduit object at 0x7f6b1c6ccb50>\nname = 'setup'\n\n    def call_optional(obj, name):\n        method = getattr(obj, name, None)\n        isfixture = hasattr(method, \"_pytestfixturefunction\")\n        if method is not None and not isfixture and callable(method):\n            # If there's any problems allow the exception to raise rather than\n            # silently ignoring them.\n>           method()\nE           TypeError: setup() takes 0 positional arguments but 1 was given\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:38: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "conduit_panniangyan_test"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az83-915"
  }, {
    "name" : "thread",
    "value" : "3695-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.conduit_panniangyan_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 18,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 18
      },
      "items" : [ {
        "uid" : "b613dee7ffa5fa75",
        "reportUrl" : "https://panniangyan.github.io/conduit/20//#testresult/b613dee7ffa5fa75",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627899646682,
          "stop" : 1627899646682,
          "duration" : 0
        }
      }, {
        "uid" : "f83dc4dad83dda5",
        "reportUrl" : "https://panniangyan.github.io/conduit/19//#testresult/f83dc4dad83dda5",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627899220819,
          "stop" : 1627899220819,
          "duration" : 0
        }
      }, {
        "uid" : "419d7053ac6468cd",
        "reportUrl" : "https://panniangyan.github.io/conduit/18//#testresult/419d7053ac6468cd",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627898435400,
          "stop" : 1627898435400,
          "duration" : 0
        }
      }, {
        "uid" : "73be3869ec7efad8",
        "reportUrl" : "https://panniangyan.github.io/conduit/17//#testresult/73be3869ec7efad8",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52653): Max retries exceeded with url: /session/f04a3cdd168c74da301d0c38b9cb3db9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca1bed6250>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627896379154,
          "stop" : 1627896379154,
          "duration" : 0
        }
      }, {
        "uid" : "2ec04070481fe55a",
        "reportUrl" : "https://panniangyan.github.io/conduit/16//#testresult/2ec04070481fe55a",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60017): Max retries exceeded with url: /session/b1a5c94c7bc7022ef76dd2ebb8ba0f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a74f7d220>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627895212751,
          "stop" : 1627895212751,
          "duration" : 0
        }
      }, {
        "uid" : "9782d02414b0c9c5",
        "reportUrl" : "https://panniangyan.github.io/conduit/15//#testresult/9782d02414b0c9c5",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=43719): Max retries exceeded with url: /session/91742e4ead70df7aa6cbcad06f4f1bd2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe18d238760>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627892996255,
          "stop" : 1627892996255,
          "duration" : 0
        }
      }, {
        "uid" : "72836773d3fddff7",
        "reportUrl" : "https://panniangyan.github.io/conduit/14//#testresult/72836773d3fddff7",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'WebDriver' object has no attribute 'webdriver'",
        "time" : {
          "start" : 1627892617374,
          "stop" : 1627892617374,
          "duration" : 0
        }
      }, {
        "uid" : "904c3ebb4398b4f9",
        "reportUrl" : "https://panniangyan.github.io/conduit/12//#testresult/904c3ebb4398b4f9",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627888455639,
          "stop" : 1627888455639,
          "duration" : 0
        }
      }, {
        "uid" : "bdd53348ee8f6a69",
        "reportUrl" : "https://panniangyan.github.io/conduit/11//#testresult/bdd53348ee8f6a69",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829932568,
          "stop" : 1627829932568,
          "duration" : 0
        }
      }, {
        "uid" : "183347a3f2c75f06",
        "reportUrl" : "https://panniangyan.github.io/conduit/10//#testresult/183347a3f2c75f06",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829830048,
          "stop" : 1627829830048,
          "duration" : 0
        }
      }, {
        "uid" : "cfb4b78b7ec6238",
        "reportUrl" : "https://panniangyan.github.io/conduit/9//#testresult/cfb4b78b7ec6238",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829049992,
          "stop" : 1627829049992,
          "duration" : 0
        }
      }, {
        "uid" : "c7eb53501efbd8ac",
        "reportUrl" : "https://panniangyan.github.io/conduit/8//#testresult/c7eb53501efbd8ac",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627828717738,
          "stop" : 1627828717738,
          "duration" : 0
        }
      }, {
        "uid" : "fb8374e619526827",
        "reportUrl" : "https://panniangyan.github.io/conduit/7//#testresult/fb8374e619526827",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627828256019,
          "stop" : 1627828256019,
          "duration" : 0
        }
      }, {
        "uid" : "a84747d23ddef301",
        "reportUrl" : "https://panniangyan.github.io/conduit/6//#testresult/a84747d23ddef301",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627827069247,
          "stop" : 1627827069247,
          "duration" : 0
        }
      }, {
        "uid" : "7ef9045816af3eee",
        "reportUrl" : "https://panniangyan.github.io/conduit/5//#testresult/7ef9045816af3eee",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627819956235,
          "stop" : 1627819956235,
          "duration" : 0
        }
      }, {
        "uid" : "eaae4f1126163bd0",
        "reportUrl" : "https://panniangyan.github.io/conduit/4//#testresult/eaae4f1126163bd0",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818411546,
          "stop" : 1627818411546,
          "duration" : 0
        }
      }, {
        "uid" : "bd66a7b594bc7cb2",
        "reportUrl" : "https://panniangyan.github.io/conduit/3//#testresult/bd66a7b594bc7cb2",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818161155,
          "stop" : 1627818161155,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "2e6437c6b9464535.json",
  "parameterValues" : [ ]
}